### ISSUE TITLE
OpenRSD update error and pivpn profile error

### ISSUE THREAD

**Issue by garfie224** [mitchellurgero/openrsd#23]
When clicking checking for openrsd updates it says "There was an error processing the update request:"

furthermore when clicking on pivpn profile page it comes up with this error "Loading the page failed. Please try again."

**Comment by mitchellurgero** [comment]
the pivpn page requires you have PiVPN installed (http://pivpn.io)

Also - can you upload logs for me to look at?

**Comment by garfie224** [comment]
I have openvpn installed won’t that work? And what logs do you need? Thanks

**Comment by mitchellurgero** [comment]
PiVPN is a specific set of scripts and tools for openvpn - and they are required for that page.

For logs, please send `/var/log/apache2/error.log`.
