### ISSUE TITLE
Dynamic loading of apt commands responses

### ISSUE THREAD

**Issue by gnanet** [mitchellurgero/openrsd#26]
Made some extensions, to allow the streaming display of the printouts that apt-get produces while in packages page, a video from apt-get upgrade:

https://youtu.be/arXw4gBSrz8

**Comment by gnanet** [comment]
Changed the stream display from `<pre>` to `<textarea>` with automatic height sizing, and autoscroll

https://youtu.be/gakWEQxZP80

**Comment by mitchellurgero** [comment]
I like it! I will merge tomorrow afternoon!

**Comment by gnanet** [comment]
as soon as i make the PR... ;)

**Comment by mitchellurgero** [comment]
Didn't realize this was just an issue on mobile lol. Let me know when you got a PR this is really good work!

**Comment by gnanet** [comment]
PR submitted.
