### ISSUE TITLE
New Plugin System

### ISSUE THREAD

**Issue by mitchellurgero** [mitchellurgero/openrsd#29]
As the name suggests.

See [PLUGINS.MD](https://github.com/mitchellurgero/openrsd/blob/master/PLUGINS.MD)

Screenshot of example plugin in action:

![openrsd-plugins](https://user-images.githubusercontent.com/4168998/42771395-ad75c850-88ec-11e8-9335-8ef20ef8d833.PNG)

**Comment by gnanet** [comment]
I just had time to sync back your master branch, so the next pet will be to migrate over my hostap dash extras to the plugin system

**Comment by mitchellurgero** [comment]
Nice, good luck!! <3

**Comment by gnanet** [comment]
Question @mitchellurgero currently the plugin system allows already great things, but after i created a distupgrade feature, i developed it further to show possible change-log of packages, and added the ability to download upgrade-able deb packages without doing the upgrades, a so called "Preload updated packages". 

To accomplish my goal to add preload package feature i had to extend `app/functions-orsd.js` and  `app/packages.php` 

You may noticed that the distupgrade was partly already added to the core :
- `page.php`  contains  "packagesdist" 
- the referred page itself is under `pages/packages-dist.php` 
- and inside `app/functions-orsd.js`  the as "apt_distupgrade" function is the clone of "apt_upgrade"

I created a plugin only to place the menu item into custom pages, but for my education i could try to place all functionality into the plugin.

To get back to my questions, if i wanted to do all this with a plugin:

- How do i add the Javascript part, so i can add  `onClick="apt_distupgrade();"` and `onClick="apt_downloadupdates();"`  functions to the `<button>` elements ?

- Is it possible/reasonable to place the php script for the  `ajaxRequest`s `url:` destination inside the plugin's folder? ( For now i added my functions to `app/packages.php` as stated above)

- I needed the arch to build the full path to the .deb packages, and then run **apt-listchanges** on the local package file. To be able to access the change-log of packages i extended `app/functions.php` **preg_match_all() "updates_filter"** to match the updated package's arch (ex: all armhf )  **Here i think the change could be included into core**

**Comment by mitchellurgero** [comment]
> How do i add the Javascript part, so i can add onClick="apt_distupgrade();" and onClick="apt_downloadupdates();" functions to the <button> elements ?

If you are putting buttons on custom pages, just add the onclick events as normal. For already made pages this is not possible at this time.

> Is it possible/reasonable to place the php script for the ajaxRequests url: destination inside the plugin's folder? ( For now i added my functions to app/packages.php as stated above)

Absolutely add them to the plugin folder. Since the user never sees the url anyway this is totally fine. And is expected. the Plugin should add all files it needs. Then just reference them from the plugin folder. This is fine. Do not add plugin functions to core. I will not accept them as plugins should be in their own repository :)

> I needed the arch to build the full path to the .deb packages, and then run apt-listchanges on the local package file. To be able to access the change-log of packages i extended app/functions.php preg_match_all() "updates_filter" to match the updated package's arch (ex: all armhf ) Here i think the change could be included into core

New features from now on should be plugins. However big changes like this I would totally consider moving to core. 


Side Note: Also make sure you pulled the repo recently. I made a few changes that fix HUGE security bugs found from earlier commits.

**Comment by gnanet** [comment]
> > How do i add the Javascript part, so i can add onClick="apt_distupgrade();" and onClick="apt_downloadupdates();" functions to the  elements ?
> 
> If you are putting buttons on custom pages, just add the onclick events as normal. For already made pages this is not possible at this time.

I was not clear enough, i need to put the javascript functions somewhere, to be able to use them on the buttons. So where / which file i should add the JS code

**Comment by mitchellurgero** [comment]
These buttons, where are they? A custom page?

**Comment by gnanet** [comment]
> New features from now on should be plugins. 
Based on your answer, the goal would be a custom-page

I am looking already at `onFootEnd($sess)`  but i had somewhere an isseu that echoing javascript code into the HTML wont execute, but i dont know if that only refers to **onload, document.ready** events

**Comment by gnanet** [comment]
I think about  echoing a <script ... src=></script> into footer referring to a true javascript file in the plugins folder

**Comment by mitchellurgero** [comment]
onFootEnd is for every page, not just the plugin. Is this javascript used only on the plugins main page? If so just throw it at the end of the onPage event you have for the plugin already.

**Comment by gnanet** [comment]
[Does the order of echod javascript matters?](https://stackoverflow.com/a/22704811/4771006)

[At least this post seems to shed a light:](https://www.daniweb.com/posts/jump/719815)

> You shouldn't load and execute code using the same <script> tag.
> And all <script> blocks should be inside the \<head> block, or at least all <script> blocks that are meant to load external code.

I will try it out on the weekend

**Comment by mitchellurgero** [comment]
For order: yes it matters. First loaded, first executed.

That quote is invalid for today's day. Scripts should be at the end of the body. Not the beginning. This optimizes load time and allows the UI to load making the page *feel* faster.
