### ISSUE TITLE
OpenRSD logs password in plaintext in auth.log

### ISSUE THREAD

**Issue by MMurphy4096** [mitchellurgero/openrsd#3]
So yeah... I pretty much just said what I had to right there; every time you log in to openrsd, it stores the password in plaintext in auth.log.

**Comment by MMurphy4096** [comment]
Yeah; it's pretty bad.  Here's a snippet of my log so that way everyone can see where to look

`Dec 16 02:08:09 leto sudo:     matt : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=/bin/bash ./app/scripts/listusers.sh
Dec 16 02:08:09 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:09 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:09 leto sudo:     matt : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=./app/bin/chkpasswd matt **IPUTHEWRONGPASSWORDHERE**
Dec 16 02:08:09 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:09 leto chkpasswd: pam_unix(system-auth:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=matt
Dec 16 02:08:11 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:23 leto sudo:     matt : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=/bin/bash ./app/scripts/listusers.sh
Dec 16 02:08:23 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:23 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:23 leto sudo:     matt : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=./app/bin/chkpasswd matt **THISONEWASTHERIGHTPASSWORD**
Dec 16 02:08:23 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:23 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:24 leto sudo:     matt : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=/bin/bash ./app/scripts/adapters.sh
Dec 16 02:08:24 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:24 leto sudo:     root : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=/sbin/ifconfig -a
Dec 16 02:08:24 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:24 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:24 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:24 leto sudo:     matt : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=/bin/bash ./app/scripts/updates_list.sh
Dec 16 02:08:24 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:24 leto sudo:     root : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=/usr/bin/apt-get --just-print upgrade
Dec 16 02:08:24 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:26 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:26 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:26 leto sudo:     matt : TTY=unknown ; PWD=/var/www/html/dashboard ; USER=root ; COMMAND=/usr/bin/who
Dec 16 02:08:26 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 16 02:08:26 leto sudo: pam_unix(sudo:session): session closed for user root
Dec 16 02:08:33 leto sudo:     matt : TTY=unknown ; PWD=/var/www/html/dashboard/app ; USER=root ; COMMAND=/bin/cat /var/log/auth.log
Dec 16 02:08:33 leto sudo: pam_unix(sudo:session): session opened for user root by (uid=0)`

**Comment by mitchellurgero** [comment]
The good news is that log is NOT internet accessible with a default install of OpenRSD. :) But still not a good thing with plain text password lol
