### ISSUE TITLE
New readme does not work on Stretch

### ISSUE THREAD

**Issue by Hwurzburg** [mitchellurgero/openrsd#34]
first there is a typo in the code block to install pre-requites...submitted a correcting pull request..
then I made a mistake in changing dirs....working now with above change

**Comment by mitchellurgero** [comment]
It says 404 because you got cloned the repo outside of the html folder... you never cd’d to the root of the web server, unless I scrolled past it lol.

**Comment by gnanet** [comment]
a default Stretch install does not have an `lsof` how come?

> Section: utils
> Priority: **standard**
> Filename: pool/main/l/lsof/lsof_4.89+dfsg-0.1_amd64.deb
> 

the alternative `netstat` command installed by **net-tools** package, needs to be installed extra, as i tested:

> Section: net
> Priority: **optional**
> Filename: pool/main/n/net-tools/net-tools_1.60+git20161116.90da8a0-1_amd64.deb
>

**Comment by mitchellurgero** [comment]
Honestly I don't know why.

**Comment by gnanet** [comment]
@mitchellurgero could you add to the `lsof` package to the `stretch apt-get install ` line, that way we could make sure all commands we use in the readme are also present. For that 4-5 letters i wouldnt make a PR extra.

**Comment by mitchellurgero** [comment]
Lighttpd is also running as www-data correct? what does the error log say for the server?

**Comment by Hwurzburg** [comment]
Which log and where?

**Comment by Hwurzburg** [comment]
found the lighttpd error log....last entry after last start:
2018-11-04 22:33:22: (log.c.217) server started 
2018-11-04 22:33:22: (server.c.1295) WARNING: unknown config-key: fastcgi.server (ignored)

**Comment by Hwurzburg** [comment]
Well, then its the latest update of Stretchs issue....since it was a clean image, and then readme followed directly...three tries...I notice there has been a large Stretch (~40MB) update/upgrade in the last few days....last week it was only a few 100KB after I imaged a system with the 10/09 releases...

**Comment by gnanet** [comment]
I think the "for sure" instruction of disabling fastcgi-php should maybe removed. I think that this time @hwurzburg did not disabled **fastcgi-php* but **fastcgi** itself.

Try please this:
```
sudo lighttpd-enable-mod fastcgi
sudo service lighttpd force-reload
```

If that helps, you should be more carefully what commands you copy and paste

**Comment by gnanet** [comment]
If the case is, that lighttpd default config was  changed, please check the output of

```
sudo lighttpd-enable-mod
```

You can CTRL+C the thing, but i would need the output of that command on the clean image you mention

**Comment by Hwurzburg** [comment]
> I think the "for sure" instruction of disabling fastcgi-php should maybe removed. I think that this time @Hwurzburg did not disabled **fastcgi-php** but **fastcgi** itself.
> 
> Try please this:
> 
> ```
> sudo lighttpd-enable-mod fastcgi
> sudo service lighttpd force-reload
> ```
> If that helps, you should be more carefully what commands you copy and paste

I assure you that I copied and pasted (on three separate occasions) what was in the readme...
enabling fastcgi and reloading worked and the web page is active...
I will reimage and update the latest Stretch and run the sudo lighttpd-enable-mod command and capture output

**Comment by gnanet** [comment]
As i read your comment about the rather huge update, i was also more confident that you havent left out the last 4 chars of a line in the middle of a bunch of lines. So i am curious about the default-off of fastcgi in the lighttpd package

**Comment by mitchellurgero** [comment]
> I assure you that I copied and pasted (on three separate occasions) what was in the readme...

@Hwurzburg Even if we are using the SAME raspbian image, you NEVER just blindly copy and paste commands as my setup can still be different from yours (Different packages are available to different Raspberry Pi's for example!!!)

**Comment by Hwurzburg** [comment]
after initial lighttpd install from first command in readme: fastcgi is disabled
Lighttpd is not installed until I execute the first install command in readme...after that all modules are disabled...
 _Disabled modules: accesslog auth cgi debian-doc dir-listing evasive evhost expire extforward fastcgi fastcgi-php flv-streaming no-www proxy rewrite rrdtool simple-vhost ssi ssl status userdir usertrack
Enabled modules: javascript-alias
Enable module:_ 
I think that fastcgi needs to be enabled at some point in the readme...I did that and everything worked on a new install

**Comment by Hwurzburg** [comment]
> > I assure you that I copied and pasted (on three separate occasions) what was in the readme...
> 
> @Hwurzburg Even if we are using the SAME raspbian image, you NEVER just blindly copy and paste commands as my setup can still be different from yours (Different packages are available to different Raspberry Pi's for example!!!)

I am afraid I dont understand the point of a readme " howto install document" then, if we are required to knowledgeable enough to ignore what is written or add to it , then why need an install document at all?

**Comment by gnanet** [comment]
> after initial lighttpd install from first command in readme: fastcgi is disabled
> Lighttpd is not installed until I execute the first install command in readme...after that all modules are disabled...
> _Disabled modules: accesslog auth cgi debian-doc dir-listing evasive evhost expire extforward fastcgi fastcgi-php flv-streaming no-www proxy rewrite rrdtool simple-vhost ssi ssl status userdir usertrack Enabled modules: javascript-alias Enable module:_
> I think that fastcgi needs to be enabled at some point in the readme...I did that and everything worked on a new install

1) I will add the enable's for all the required modules then
2) I love the US, but as a hungarian, non-native english, i usually do not trust 1:1 copying of install instructions, even if the "BEWARE THIS IS ONLY A DRAFT" | "THESE INSTRUCTIONS ARE NOT COMPLETE" | "BEWARE WET FLOOR" signs are missing

The point is, altough the instructions try to be as complete as possible, there may be points we missed, and this is where you come in, and can deliver useful input. 

Sometimes, it is causing confusion, while we try to understand if our instructions are incomplete, or the instructions were not followed, of we wrote some bullshit that was followed letter-by-letter.

Anyways thank you for the input, it helped me to extend the readme for stretch+lighty part

**Comment by Hwurzburg** [comment]
Thanks...happy to help...the application is very nice and useful...but a lot of users will be like me....novices to Linux...I had never done anything but some simple porting of Arduplane code to new flight contoller boards in Linux, until two weeks ago when I got a RPI...now I have a PiVPN/Pihole server on my home network, a touch screen RPI based pc, and putting a RPI0W based cellular telemetry radio in my long range FPV RC planes...a lot to come up to speed on for a 70 yr old retired EE...thanks again
