### ISSUE TITLE
shellinabox not working on dashboard

### ISSUE THREAD

**Issue by roleed** [mitchellurgero/openrsd#36]
Hi, 

I've installed exactly via what the README says, running raspbian stretch i just get a blank box on the dashboard when viewing shell in a box.

**Comment by gnanet** [comment]
1. If you are using Google Chrome, please open the dev-console (F12 if i remember) and then try to navigate to the "Shell in a box" menuitem, and look for any warning or errors.

1. Could you please check if you can directly reach the shell-in-a-box url itself:
http://ADDRESS-OF-YOUR-PI:4200/

1. Last thing if above things fail, check if and on what port the shellinaboxd is listening:
`sudo netstat -tulpn | grep shellinaboxd`
Should respond similar to this:
`tcp        0      0 0.0.0.0:4200            0.0.0.0:*               LISTEN      742/shellinaboxd`

**Comment by mitchellurgero** [comment]
@roleed I assume you are trying to view Shell-In-A-Box via OpenRSD, if so, unfortunately this might be an issue with Shell-In-A-Box. I am just using an iFrame to the SIAB UI on port 4200. As @gnanet  asked, are you able to connect directly to Shell-In-A-Box?

What is your OS version, PHP version, Apache version, etc? Also, any logs you can share would be super helpful too.

**Comment by roleed** [comment]
Sorry I have may posted the issue to soon without a proper look into how it works. I believe the issue is because it uses port 4200 (which I didn't realise) which is not forwarded on the router I access it remotely from, Ill close this for now as is probably not an issue - will re-open once im able to forward the port and still an issue.

**Comment by mitchellurgero** [comment]
@roleed It is not recommended to serve OpenRSD from your router to the internet. It is a huge security risk  as this software is still in beta.

I recommend accessing the Pi using a VPN instead which is much safer as only you would have access to the VPN.
