### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by Scott1974-1** [mitchellurgero/openrsd#4]
I installed OpenRSD as per the install instructions and when I go to the page to login it won't accept my pi password. I have tried everything including changing the password and nothing works. it just says incorrect password then after a few tries it says too many attempts contact your administrator.

any ideas.

I'm running the newest version of jessie lite.

thank you

**Comment by maxgrass** [comment]
@Scott1974-1 Why creating 2 issues on different project without searching for already opened issues?
Please delete them, as it won't make development quicker, it'll add more clutter. If you have more usefull information, comment in https://github.com/mitchellurgero/openrsd/issues/2

**Comment by mitchellurgero** [comment]
This also only works on pi3, I don't believe the latest raspbian for rpi2 will work on this.
