### ISSUE TITLE
request interface to create a new user account 

### ISSUE THREAD

**Issue by sanfx** [mitchellurgero/openrsd#43]
I want to request for an interface to create new user account on pi without logged in user  which currently is being done by add user feature.

New user account creation can be authenticated by email would be great.

with feature like if user not verified by admin then user expires from raspberry pi.

**Comment by mitchellurgero** [comment]
This script is not meant to be used on an internet facing raspberry pi (should be used locally or over a VPN!) And as such, this feature does not fall under this security scope set in place by the readme. 

Unfortunately I will not be implementing this feature.

**Comment by sanfx** [comment]
I wanted to use over local network multiple family members intending to store their mobile content to local NAS Storage. Currently they ask me to create a user account which I wanted to be automated.
