### ISSUE TITLE
Can't sign in through the web interface.

### ISSUE THREAD

**Issue by jakehawken** [mitchellurgero/openrsd#48]
Using my raspberry pi account and password doesn't work as the instructions say it should. I never get past the login screen.

**Comment by mitchellurgero** [comment]
Take a look at the logs. You are likely running openrsd under an account that doesn’t have Sudo rights

**Comment by jakehawken** [comment]
Cool. Where do I find those logs, and what would they say if that were the case?

**Comment by juskuu** [comment]
I have the same problem. I'm running it on the pi user,

I cant seem to find any apache logs though. my  "/var/log/"  had these in it:

> `alternatives.log  dpkg.log        messages          syslog.1
apt               faillog         pihole            unattended-upgrades
auth.log          firebird        pihole-FTL.log    user.log
boot.log          fontconfig.log  pihole-FTL.log.1  wtmp
bootstrap.log     kern.log        pihole.log        Xorg.0.log
btmp              lastlog         pihole.log.1      Xorg.0.log.old
daemon.log        lightdm         private           Xorg.1.log
debug             lighttpd        syslog
`

**Comment by mitchellurgero** [comment]
Check out syslog. Since openrsd is its own service, it defaults to logging there.

**Comment by juskuu** [comment]
- Feb 12 18:08:26 pi-hole systemd[1]: Started Permit User Sessions.
- Feb 12 18:08:26 pi-hole systemd[1]: openrsd.service: Main process exited, code=exited, status=217/USER
- Feb 12 18:08:26 pi-hole systemd[1]: openrsd.service: Failed with result 'exit-code'.
- Feb 12 18:08:29 pi-hole systemd[1]: openrsd.service: Service RestartSec=3s expired, scheduling restart.
- Feb 12 18:08:29 pi-hole systemd[1]: openrsd.service: Scheduled restart job, restart counter is at 1.
- Feb 12 18:08:29 pi-hole systemd[1]: Stopped OpenRSD Service.
- Feb 12 18:08:29 pi-hole systemd[1]: Started OpenRSD Service.
- Feb 12 18:08:29 pi-hole systemd[748]: openrsd.service: Failed to determine user credentials: No such process
- Feb 12 18:08:29 pi-hole systemd[748]: openrsd.service: Failed at step USER spawning /usr/bin/php: - No such process
- Feb 12 18:08:29 pi-hole systemd[1]: openrsd.service: Main process exited, code=exited, status=217/USER
- Feb 12 18:08:29 pi-hole systemd[1]: openrsd.service: Failed with result 'exit-code'.


It loops this same error, only  the restart counter is different each time.
