### ISSUE TITLE
User not listed

### ISSUE THREAD

**Issue by mengelsen** [mitchellurgero/openrsd#50]
I created a new user via SSH. This user is a member of the 'sudo' group. However I do not see this user listed within the "Users" page, within OpenRSD. 

Is this expected behavior? In other words, should the **only** users listed (on the "Users" page) be the users created via the OpenRSD webGUI?

**Comment by mitchellurgero** [comment]
This is strange - it should work no problem. Can the user created via ssh login to openrsd?

**Comment by mengelsen** [comment]
The only user who can login to OpenRSD is "pi". I am unable to login as "root", or as the user I created via SSH.

**Comment by mengelsen** [comment]
Is this behavior occurring because I modified the /etc/apache2/apache2.conf file?

(OpenRSD: Advanced Installation instructions, Step #3)
I changed the "User" and "Group" values to "pi".
```
User pi
Group pi
```

**Comment by mitchellurgero** [comment]
No, the users listed must have a valid login bin in /etc/passwd

**Comment by mengelsen** [comment]
Understood. Well...**all** of the users I am trying to authenticate with (via the pi Admin Panel) exist within /etc/passwd.

Such as: root, openrsd, and webadmin

**Comment by mengelsen** [comment]
I also attempted to 'switch users' via a SSH session.

```
pi@pi:~ $ su - openrsd
Password: 
su: Authentication failure
pi@pi:~ $ su - openrsd
Password: 
su: Authentication failure
pi@pi:~ $ su - openrsd
Password: 
openrsd@pi:~$ exit
logout
```

OpenRSD did not record these failed authentication attempts within:
Basic Configuration -> Users -> Authentication Failures

**Comment by mitchellurgero** [comment]
Authentication failure box is for OpenRSD (Software, not user) authentication fails.System authentication fails will be under Logs -> auth.

**Comment by mengelsen** [comment]
> Authentication failure box is for OpenRSD (Software, not user) authentication fails.System authentication fails will be under Logs -> auth.

Ahhh. Ok. That makes sense.

**Comment by mitchellurgero** [comment]
Oh users listed in /etc/passwd that don't use some type of shell as login (like /bin/bash) will not show up under users in OpenRSD. An example would be pi should show up, but NOT openrsd service user

**Comment by mengelsen** [comment]
> Oh users listed in /etc/passwd that don't use some type of shell as login (like /bin/bash) will not show up under users in OpenRSD. An example would be pi should show up, but NOT openrsd service user

Great idea. However, I think all of the users (that interest me) are using the same interactive shell.
```
webadmin:x:999:995::/home/webadmin:/bin/bash
openrsd:x:998:994::/home/openrsd:/bin/bash
pi:x:1000:1000:,,,:/home/pi:/bin/bash
root:x:0:0:root:/root:/bin/bash
```

**Comment by mengelsen** [comment]
> Oh users listed in /etc/passwd that don't use some type of shell as login (like /bin/bash) will not show up under users in OpenRSD. An example would be pi should show up, but NOT openrsd service user

I am still unable to view users (within OpenRSD) that possess the same login shell as the "pi" user. (Which is "/bin/bash")

**Comment by mengelsen** [comment]
Today I (tried to) create a new user, using the "Add User" button within OpenRSD.

The resulting output looked successful (See attached image.) However I found myself unable to sign into OpenRSD with this newly-created user account. I tried switching to this user, via the terminal, but was unable to do so. (Authentication failure. (Perhaps this is because I am accessing OpenRSD via HTTPS? IDK.)

I changed the user's password, via the the terminal. I can now switch to the user within the terminal; but I (still) can not log into OpenRSD as this newly-created user. Also, this user is not listed within the "Users" section of OpenRSD.

Thoughts?
<img width="1673" alt="OpenRSD Users" src="https://user-images.githubusercontent.com/6595983/86494581-bc6dea80-bd43-11ea-91cd-aa0ddc4af5e8.png">

**Comment by mitchellurgero** [comment]
I'll look into this bug this weekend - in the mean time, the user "pi" still works?

**Comment by mengelsen** [comment]
> The user "pi" still works?
Yes. I can definitely sign into OpenRSD using the "pi" user.

**Comment by mengelsen** [comment]
> I'll look into this bug this weekend - in the mean time, the user "pi" still works?

Just checking in to see if there were any breakthroughs (as to why users created using OpenRSD aren't appearing within the Web Interface & their passwords are misconstrued).
