### ISSUE TITLE
Unique URL

### ISSUE THREAD

**Issue by mengelsen** [mitchellurgero/openrsd#52]
Is it possible to bookmark a specific page within OpenRSD? (Such as "Applications & Scripts" or "Cron Configuration".)

Currently, it appears as though the URI never changes, as I switch from page to page. It always remains the same.
https://FQDN_HERE/openrsd/index.php#

Thanks!

**Comment by mitchellurgero** [comment]
I wrote OpenRSD as a Javascript app - so the URL is never changed between pages. Unfortunately this means that no bookmarks can be made here.
