### ISSUE TITLE
Account not working

### ISSUE THREAD

**Issue by mcosti** [mitchellurgero/openrsd#7]
Hello. I am trying to login with account "pi" and the password I've set and I've logged with into SSH, so it's not wrong.
Still, it tells me everytime it is wrong. Can you please help me?

**Comment by mitchellurgero** [comment]
Wh

**Comment by mcosti** [comment]
Hey. It's Pi3.
I am pretty sure apache is running under www-data.

**Comment by mitchellurgero** [comment]
Apache needs to run as the user "pi" and group "pi" as explain in the readme. This config is under /etc/apache/apache.config

**Comment by mitchellurgero** [comment]
No update on this in months. Closing.
