### ISSUE TITLE
block router ip

### ISSUE THREAD

**Issue by leoncoolmoon** [mitchellurgero/openrsd#9]
i open nat on my router to allow remote access, but due to wrong typo of password, my router has been blocked by pi. Therefore, i can not access openrsd through any account remotely with any ip. could you fix it pls

**Comment by mitchellurgero** [comment]
Hello friend,
Since you are using OpenRSD in a way that was not intended use and was recommended against, I cannot assist much. All I can say is look into the blocked_ip folder in the root of the pi's web server.

**Comment by leoncoolmoon** [comment]
@mitchellurgero  what do you mean by "using OpenRSD in a way that was not intended use " ? what is OpenRSD intended todo?

**Comment by leoncoolmoon** [comment]
can you add a white list since you designed a black list?

**Comment by mitchellurgero** [comment]
OpenRSD was not designed to be used across the internet but used with VPN or on LAN only.

I can probably make a whitelist - I’ll look into it.

**Comment by leoncoolmoon** [comment]
thanks

Sent from my ecophone

Apr 26, 2018 11:10 PM wrote on Mitchell Urgero <notifications@github.com>:

OpenRSD was not designed to be used across the internet but used with VPN or on LAN only.

I can probably make a whitelist - I’ll look into it.

**Comment by spikopath** [comment]
I was trying to access OpenRSD remotely to manage PiVPN profiles. I realise I cannot do this remotely.

I managed a workaround for remote management with extplorer and ssh (pivpn-cli) but this is far from ideal.

**Comment by mitchellurgero** [comment]
> I was trying to access OpenRSD remotely to manage PiVPN profiles. I realise I cannot do this remotely.
> 
> I managed a workaround for remote management with extplorer and ssh (pivpn-cli) but this is far from ideal.

First off, wrong place to put this. Open your own issue next time please.

Secondly, It is NOT recommended to use OpenRSD without VPN access.  Setup OpenRSD, setup Pi-VPN then once done, disconnect from your wifi and connect to the new VPN you created. Once that is done you can access OpenRSD as normal.

Essentially:

1. Install OpenRSD (Make sure you can sign in locally)
2. Install Pi-VPN
3. Create at least 1 vpn profile
4. Add port 1194 to your modem or firewall as a port forward to the STATIC IP of the RPi you are using for OpenRSD & VPN
5. Put the VPN profile you just made onto another device, external to your network (work computer, cell phone, etc)
6. Make sure you are on a different network than the RPi or the VPN will not work.
7. Connect to the VPN.
8. Try to access the RPi using it's LAN IP. This will be different from it's VPN IP.
9. Login and confirm everything is work.


IF the above does not work, I can assist in troubleshooting via email or phone call, however I charge for that type of service.
